# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  ACR_NAME: acrapidemogsilva001  # Substitua pelo nome do seu Azure Container Registry
  IMAGE_NAME: apitempogsilva  # Nome da imagem no ACR

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Login no Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login no Azure Container Registry (ACR)
      run: az acr login --name $ACR_NAME

    - name: Construir e enviar a imagem Docker para o ACR
      run: | 
        TAG=$(date +%Y%m%d%H%M%S)  # Gera um timestamp único (YYYYMMDDHHMMSS)
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$TAG .
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$TAG

    - name: Logout do Docker
      run: docker logout $ACR_NAME.azurecr.io
